spring:
  config:
    activate:
      on-profile: prod

  application:
    name: deulbull-performance-api

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    hibernate:
      ddl-auto: update
      # ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:none}

  servlet:
    multipart:
      max-file-size: ${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE:50MB}
      max-request-size: ${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE:100MB}

server:
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    export:
      prometheus:
        enabled: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

sms:
  api:
    key: ${SMS_API_KEY}
    secret: ${SMS_API_SECRET}
  from: ${SMS_FROM}

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
    region:
      static: ${AWS_REGION_STATIC}

discord:
  booking:
    webhook: ${DISCORD_BOOKING}
  log:
    webhook: ${DISCORD_LOG}
